/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as TerminaisRouteImport } from './routes/terminais'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CaixaRouteImport } from './routes/caixa'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as ApiWebhooksMercadopagoRouteImport } from './routes/api/webhooks/mercadopago'
import { Route as ApiPublicNotifyAdminRouteImport } from './routes/api/public/notify-admin'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminaisRoute = TerminaisRouteImport.update({
  id: '/terminais',
  path: '/terminais',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaRoute = CaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMercadopagoRoute = ApiWebhooksMercadopagoRouteImport.update({
  id: '/api/webhooks/mercadopago',
  path: '/api/webhooks/mercadopago',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyAdminRoute = ApiPublicNotifyAdminRouteImport.update({
  id: '/api/public/notify-admin',
  path: '/api/public/notify-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/assinatura': typeof AssinaturaRoute
  '/caixa': typeof CaixaRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/fornecedores': typeof FornecedoresRoute
  '/login': typeof LoginRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/super-admin': typeof SuperAdminRoute
  '/terminais': typeof TerminaisRoute
  '/vendas': typeof VendasRoute
  '/api/public/notify-admin': typeof ApiPublicNotifyAdminRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
}
export interface FileRoutesByTo {
  '/assinatura': typeof AssinaturaRoute
  '/caixa': typeof CaixaRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/fornecedores': typeof FornecedoresRoute
  '/login': typeof LoginRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/super-admin': typeof SuperAdminRoute
  '/terminais': typeof TerminaisRoute
  '/vendas': typeof VendasRoute
  '/api/public/notify-admin': typeof ApiPublicNotifyAdminRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/assinatura': typeof AssinaturaRoute
  '/caixa': typeof CaixaRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/fornecedores': typeof FornecedoresRoute
  '/login': typeof LoginRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/super-admin': typeof SuperAdminRoute
  '/terminais': typeof TerminaisRoute
  '/vendas': typeof VendasRoute
  '/api/public/notify-admin': typeof ApiPublicNotifyAdminRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/assinatura'
    | '/caixa'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/estoque'
    | '/financeiro'
    | '/fornecedores'
    | '/login'
    | '/produtos'
    | '/relatorios'
    | '/super-admin'
    | '/terminais'
    | '/vendas'
    | '/api/public/notify-admin'
    | '/api/webhooks/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assinatura'
    | '/caixa'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/estoque'
    | '/financeiro'
    | '/fornecedores'
    | '/login'
    | '/produtos'
    | '/relatorios'
    | '/super-admin'
    | '/terminais'
    | '/vendas'
    | '/api/public/notify-admin'
    | '/api/webhooks/mercadopago'
  id:
    | '__root__'
    | '/assinatura'
    | '/caixa'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/estoque'
    | '/financeiro'
    | '/fornecedores'
    | '/login'
    | '/produtos'
    | '/relatorios'
    | '/super-admin'
    | '/terminais'
    | '/vendas'
    | '/api/public/notify-admin'
    | '/api/webhooks/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AssinaturaRoute: typeof AssinaturaRoute
  CaixaRoute: typeof CaixaRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  EstoqueRoute: typeof EstoqueRoute
  FinanceiroRoute: typeof FinanceiroRoute
  FornecedoresRoute: typeof FornecedoresRoute
  LoginRoute: typeof LoginRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SuperAdminRoute: typeof SuperAdminRoute
  TerminaisRoute: typeof TerminaisRoute
  VendasRoute: typeof VendasRoute
  ApiPublicNotifyAdminRoute: typeof ApiPublicNotifyAdminRoute
  ApiWebhooksMercadopagoRoute: typeof ApiWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminais': {
      id: '/terminais'
      path: '/terminais'
      fullPath: '/terminais'
      preLoaderRoute: typeof TerminaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa': {
      id: '/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof CaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/mercadopago': {
      id: '/api/webhooks/mercadopago'
      path: '/api/webhooks/mercadopago'
      fullPath: '/api/webhooks/mercadopago'
      preLoaderRoute: typeof ApiWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-admin': {
      id: '/api/public/notify-admin'
      path: '/api/public/notify-admin'
      fullPath: '/api/public/notify-admin'
      preLoaderRoute: typeof ApiPublicNotifyAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AssinaturaRoute: AssinaturaRoute,
  CaixaRoute: CaixaRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  EstoqueRoute: EstoqueRoute,
  FinanceiroRoute: FinanceiroRoute,
  FornecedoresRoute: FornecedoresRoute,
  LoginRoute: LoginRoute,
  ProdutosRoute: ProdutosRoute,
  RelatoriosRoute: RelatoriosRoute,
  SuperAdminRoute: SuperAdminRoute,
  TerminaisRoute: TerminaisRoute,
  VendasRoute: VendasRoute,
  ApiPublicNotifyAdminRoute: ApiPublicNotifyAdminRoute,
  ApiWebhooksMercadopagoRoute: ApiWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
